### ISSUE TITLE
Occasional Plugin Crash

### ISSUE THREAD

**Issue by rcoletti116** [peledies/Homebridge-Ambient-Weather-Temperature-Sensor#5]
**Describe The Bug:**

The plugin will occasionally crash on updateData.

**To Reproduce:**

It's unclear if this is triggered based on certain values.

**Expected behavior:**

Plugin should update data and not crash.

**Logs:**

```
TypeError: Cannot read properties of undefined (reading 'value')
    at TemperatureAccessory.updateData (/usr/local/lib/node_modules/homebridge-ambient-weather-sensors/src/temperatureAccessory.ts:56:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

TypeError: Cannot read properties of undefined (reading 'value')
    at HumidityAccessory.updateData (/usr/local/lib/node_modules/homebridge-ambient-weather-sensors/src/humidityAccessory.ts:53:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Plugin Config:**

```json
{
    "name": "AmbientWeatherSensors",
    "apiKey": "xx",
    "applicationKey": "xx",
    "temperatureSensors": true,
    "humiditySensors": true,
    "solarRadiationSensors": false,
    "platform": "AmbientWeatherSensors",
    "_bridge": {
        "username": "0E:9E:A4:19:5C:3F",
        "port": 39031
    }
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.2.1
* **Homebridge Version**: 1.7.0
* **Node.js Version**: 20.10.0
* **NPM Version**: 10.2.3
* **Operating System**:  hb-service

**Comment by WotAGitUR** [comment]
I have a similar issue. The plugin makes the API call to ambient and gets this
`ERROR: invalid json response body at (API call) reason: Unexpected token '<', "<!DOCTYPE "... is not valid JSON`
Followed by
`TypeError: Cannot read properties of undefined (reading 'filter')
    at TemperatureAccessory.updateData (/var/lib/homebridge/node_modules/homebridge-ambient-weather-sensors/src/temperatureAccessory.ts:52:28)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`
At which point it stops making further requests and the only option is to restart Homebridge :(

**Comment by Yositimy** [comment]
As information, I've also seen something similar. I've been seeing this in the logs prior to a restart


[06/02/2025, 04:14:23] [AmbientWeatherSensors] ERROR: invalid json response body at https://rt.ambientweather.net/v1/devices?applicationKey=4bffcc0e98e1438f91921521a75c1b61f0278d5226f541c2a3efe5bf5fc81354&apiKey=57120c5e96e64ad7ad47045986b84cf6a7d26707e41442b1829eec6a79ef70f9 reason: Unexpected token < in JSON at position 0
[06/02/2025, 04:14:23] TypeError: Cannot read properties of undefined (reading 'filter')
    at TemperatureAccessory.updateData (/var/lib/homebridge/node_modules/homebridge-ambient-weather-sensors/src/temperatureAccessory.ts:52:28)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[06/02/2025, 04:14:23] Got SIGTERM, shutting down Homebridge...


Debian GNU/Linux Bookworm (12)
v18.19.0

Plug in v1.2.2

**Comment by peledies** [comment]
Hey everyone. 

I believe this is the same issue that is being worked in issue https://github.com/peledies/homebridge-ambient-weather-sensors/issues/9 

There should be a fix for this in the near future.

Im going to close this issue since i believe it to be a duplicate. If you have further information please add it to the linked issue.

Thanks
